version: 2
updates:
  # --- NPM: security only ----
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    groups:
      npm-security:
        applies-to: security-updates
        patterns: [ "*" ]
    labels: [ "security", "testing" ]
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: [ "*" ]
    cooldown:
      default-days: 7
