on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'The type of semantic version increment to make (one of major, minor, patch, or prerelease)'
        required: true
        default: 'patch'
      dry_run:
        description: 'If true, only calculate the new version and exit successfully.'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          npm install
          npm run test
          npm run build
      - name: Commit and Push
        run: |
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "Build Release"
          git push
      - uses: ./action.yml
        with:
          bump: ${{ github.event.inputs.bump }}
          dry_run: ${{ github.event.inputs.dry_run }}